# elevate permissions
sudo: required
language: generic
services: 
    - docker

before_install:
    - docker build -t jonschmedt/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jonschmedt/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-806118274425"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
