# elevate permissions
sudo: required
language: generic
services: 
    - docker
before_install:
    - docker build -t jonschmedt/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true jonschmedt/docker-react npm run test -- --coverage